### ISSUE TITLE
RuntimeError: Command context mismatch. Got , expected 0

### ISSUE THREAD

**Issue by philipp-schmidt** [ci4rail/io4edge-client-python#6]
We have an MIO01 and get the following issue trying out the examples:

```
$ python3 examples/binaryiotypea/main.py 10.0.0.31:9999
Connecting to 10.0.0.31:9999
Traceback (most recent call last):
  File "main.py", line 85, in <module>
    main()
  File "main.py", line 20, in main
    n_channels = binio_client.describe().numberOfChannels
  File "/home/xxx/.local/lib/python3.8/site-packages/io4edge_client/binaryiotypea/client.py", line 45, in describe
    self._fb_client.describe(Pb.ConfigurationDescribe(), fs_response)
  File "/home/xxx/.local/lib/python3.8/site-packages/io4edge_client/functionblock/client.py", line 81, in describe
    fb_res = self._command(fb_cmd)
  File "/home/xxx/.local/lib/python3.8/site-packages/io4edge_client/functionblock/client.py", line 174, in _command
    raise RuntimeError(
RuntimeError: Command context mismatch. Got , expected 0
```

```
$ pip3 list | grep io4edge
io4edge-client               0.3.0
```

**Comment by KlausPopp** [comment]
You are using the wrong port. The binary IO function of the MIO01 is on port 10002. So please try: 
```
python3 examples/binaryiotypea/main.py 10.0.0.31:10002
```

N.B: Is there a special reason why you are using IP addresses rather mdns names?

**Comment by philipp-schmidt** [comment]
Thanks, that fixed it. We couldn't find a port specification in the documentation, but the go client had a port 9999 somewhere in the examples.

mdns doesn't seem to work:
(replaced our UUID with zeroes, it is correct though, we double checked it)

```
$ python3 test.py S103-MIO01-00000000-0000-0000-0000-000000000000
Looking for service _io4edge_binaryIoTypeA._tcp.local. S103-MIO01--00000000-0000-0000-0000-000000000000._io4edge_binaryIoTypeA._tcp.local.
Connecting to None:0
Traceback (most recent call last):
  File "test.py", line 85, in <module>
    main()
  File "test.py", line 17, in main
    binio_client = binio.Client(args.addr)
  File "/home/xxx/.local/lib/python3.8/site-packages/io4edge_client/binaryiotypea/client.py", line 15, in __init__
    self._fb_client = FbClient("_io4edge_binaryIoTypeA._tcp", addr, command_timeout)
  File "/home/xxx/.local/lib/python3.8/site-packages/io4edge_client/functionblock/client.py", line 19, in __init__
    self._client = BaseClient(addr, service)
  File "/home/xxx/.local/lib/python3.8/site-packages/io4edge_client/base/client.py", line 16, in __init__
    self._transport = SocketTransport(ip, port)
  File "/home/xxx/.local/lib/python3.8/site-packages/io4edge_client/base/socket_transport.py", line 11, in __init__
    s.connect((host, port))
TypeError: str, bytes or bytearray expected, not NoneType
```

**Comment by KlausPopp** [comment]
The MIO01 has three different services: two for analog inputs, one for binary I/O. You need to specify which service you want to use:

```
S103-MIO01-00000000-0000-0000-0000-000000000000-binaryIoTypeA
```
Please read https://docs.ci4rail.com/edge-solutions/modusio/mio01/quick-start-guide/

**Comment by philipp-schmidt** [comment]
Works well now, thanks for the pointer!
